### ISSUE TITLE
Sugestion: Return orriginal image if resize is same size

### ISSUE THREAD

**Issue by torrentails** [jmagnusson/Flask-Resize#10]
I noticed that when using a resize size that was the same size as the original file or when specifying a larger size with `upscale=False`, that a hashed cache file was still created.

I haven't delved into the code enough so I don't know if the cached file is a direct copy but even if it is, at best Flask-Resize is creating excess duplicate files, which could be a problem on a large image cdn and, at worst, is performing excess processing as well to produce the same image, which results in extra cpu usage and possibly a loss in quality.

I would recommend, if no other transformations of the image need to be performed and the requested size is the same as the original size, then Flask-Resize should serve the original image. perhaps add another possible parameter and call it `force_cache` or similar, and default it to `False`; setting the parameter to `True` will then force Flask-Resize to produce a cached image, even if size is the same as the original.

**Comment by jmagnusson** [comment]
Hi @torrentails,

Thanks for taking your time to think through this. I would imagine that the code still generates a new cache file when `upscale=False` and equal/larger dimensions are encountered. Your idea would be a great addition to the package. I don't have the time right now to implement it, but I'll leave this ticket open for when I do.

**Comment by jmagnusson** [comment]
@torrentails I'm going to go ahead and close this. I'm not sure I like the ambiguity that it would introduce to not create a generated image as per the arguments that were passed in. If you'd create a PR with accompanying tests I'd gladly take a look at it.
