### ISSUE TITLE
Update / Clear cache

### ISSUE THREAD

**Issue by MrLeeh** [jmagnusson/Flask-Resize#12]
If I replace an image by another one I will still see the same old image if I use `resize` option. I figured out the only way to get the new image is to delete the `cache` directory so that all images get rebuilt. Would be great to have a function `clear_cache` or even being able to rebuild the cache.

**Comment by jmagnusson** [comment]
Hi @MrLeeh,

For performance reasons there is no check in Flask-Resize if the source image has changed. I'm not sure there is a good way to do this without sacrificing performance.

A clear cache function is definitely something that could be implemented if the need is there, though usually it's not a problem to just delete the `cache` directory. Generally I just implement what I need from this library, but feel free to submit a PR with the functionality you want included.
