### ISSUE TITLE
Handling Redis authentication

### ISSUE THREAD

**Issue by DuncanBetts** [jmagnusson/Flask-Resize#19]
Hi

I see that there is a key option, but unless I'm mistaken, this is not for providing a password.
Is there a way for me to do so? Presently I've disabled authentication, but I would like to re-enable it before running my production server.

Whilst I'm here, would just like to say thank you for creating Flask-Resize, it's very nice 👍.

**Comment by jmagnusson** [comment]
@DuncanBetts Thanks for the kind words, much appreciated 😊

I've added the option `RESIZE_REDIS_PASSWORD` in version 2.0.3. Let me know if it works or not, haven't tested it too thoroughly...

**Comment by DuncanBetts** [comment]
Great, thanks very much. I haven't tested this extensively, but I re-enabled authentication on the redis server and Flask-Resize is successfully connecting, so I'd say it's working 🚀 .
