### ISSUE TITLE
Image resized but no content (grey content)

### ISSUE THREAD

**Issue by goors** [jmagnusson/Flask-Resize#4]
I am having trouble with Flask-Resize. Image is resized but it is just grey. I got only filename on grey background.

Take a look.
http://imgur.com/dPJJAn9

My img_path is ok. When I do src="{{ img_path }}" image is shown. Bu on "{{ img_path|resize('80x80') }}" it is just grey.

**Comment by antani** [comment]
For me the issue persist - the image is rendered with the image url
like : http://images3.uread.com/productimages/mainimages/682/9788131708682.jpg
http://imgur.com/zK6EWnT (the image contains the URL)
My flask template looks like:
<td><img src="{{r.img|resize('600x600', placeholder=True, fill=1, quality=50,anchor='center')}}"/>{{r.img}}</td>
