### ISSUE TITLE
Blank images created with valid URLs

### ISSUE THREAD

**Issue by antani** [jmagnusson/Flask-Resize#5]
For me the issue persist - the image is rendered with the image url
like as text: http://images3.uread.com/productimages/mainimages/682/9788131708682.jpg
http://imgur.com/zK6EWnT (the image contains the URL)

**Comment by jmagnusson** [comment]
I'm so sorry, I missed this issue somehow. Could you clean your cache directory and try version `0.25`? There was a bug that caused no exception to be raised when the image file was not found.

**Comment by jmagnusson** [comment]
I'm assuming that you fixed this issue, @antani. If you still have this problem you can re-open the issue.
