### ISSUE TITLE
Getting error when running pip or setup.py

### ISSUE THREAD

**Issue by calcutec** [jmagnusson/Flask-Resize#6]
Would like to try the library but am getting the following error related to the fix for :https://github.com/tweepy/tweepy/issues/533. 

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    requirements = parse_requirements('requirements.txt', session=uuid.uuid1())
TypeError: parse_requirements() got an unexpected keyword argument 'session'

**Comment by jmagnusson** [comment]
Fixed in 0.2.4 that should now be able to install through pip. Thanks for noticing the error.
