### ISSUE TITLE
Incorrect cache file path on Windows

### ISSUE THREAD

**Issue by torrentails** [jmagnusson/Flask-Resize#8]
When running Flask-Resize under windows, the generated cache path is invalid as it uses the OS libraries to generate the file path.

Eg when using `RESIZE_URL='http://127.0.0.1:5000'` and `RESIZE_ROOT='./static/images/'` results in the cache path `http://127.0.0.1:5000\static/images/cache/<hashed filename>`

The backslah after the `RESIZE_URL` is invalid as a web address.

**Comment by jmagnusson** [comment]
@torrentails This should be fixed now that 2.0 is here with Windows support (at least according to AppVeyor CI 😅). Feel free to test it and report any issues you might find.
